### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by lucasgrocha** [devlucasrocha/tictactoe#1]
> **Todo list:**

- [ ] Create a bot to play againts you
- [ ] Add songs for X and O players
- [ ] Use cookies/sessions for storage your points
- [ ] Improve the styleshment
